name: moni
description: "A financial tracking app for Mongolian banks"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  csv: ^5.1.1
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  sqflite: ^2.3.2
  intl: ^0.18.1
  provider: ^6.1.1
  flutter_colorpicker: ^1.1.0
  share_plus: ^7.2.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true